### PR TITLE
Fix keyword argument in emojize

### PR DESCRIPTION
**Pull request by lbariogl**
Fix a keyword argument in emojize. The following error was raised:
```
message = emojize(message, use_aliases=True)
TypeError: emojize() got an unexpected keyword argument 'use_aliases'
```

### CODE REVIEW

**Comment by lbariogl** [comment]
Hi, I really like ntfy and I have been using it for years. I have recently realised that emoji were not working anymore.
I had to make this change in order to make it work on Ubuntu 22.04

**Comment by lbariogl** [comment]
I do not understand why, but the old version is ok in macOS (python@3.9), and the new one in Ubuntu 22.04 (python@3.8).
Closing for now
